---
# tasks file for ansible-wireguard
- name: NFTABLES | Deploy nftables-service unit
  ansible.builtin.template:
    src:   nftables.service.j2
    dest:  /etc/systemd/system/nftables.service
    owner: root
    group: root
    mode:  '0755'
- name: NFTABLES | Deploy rules config file
  ansible.builtin.template:
    src:   nftables.conf.j2
    dest:  /etc/nftables.conf.new
    owner: root
    group: root
    mode:  '0755'
- name: NFTABLES | Copy nftable-service bin
  copy:
    src:   nftables-service
    dest:  /usr/local/sbin/nftables-service
    owner: root
    group: root
    mode:  '0755'
- name: NFTABLES | create varlibnftables
  file:
    path:  /var/lib/nftables
    state: directory
    mode:  '0700'
- name: NFTABLES | Enable nftables on boot
  systemd:
    name:  "nftables"
    enabled: yes
    daemon_reload: yes

