---
# Install Darix Repository
- name: NFTABLES | SLES | Install Darix Repo
  zypper_repository:
    name:   home-darix-apps
    repo:  "http://download.opensuse.org/repositories/home:/darix:/apps/SLE_{{ ansible_distribution_major_version }}_SP{{  ansible_distribution_version.split('.')[1] }}/"
    auto_import_keys: yes
    priority: 101 



# install packages
- name: NFTABLES | SLES | Install Wireguard
  zypper:
    name: "{{ nftables_sles_packages }}"
    state: latest
    update_cache: yes

